"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

const ENDPOINT = "https://ybjoayhahbifcrrrykln.supabase.co/functions/v1/create-landing-request";
const ANALYTICS_ENDPOINT = "https://ybjoayhahbifcrrrykln.supabase.co/functions/v1/track-landing-event";
const MAX_PHOTO_BYTES = 8 * 1024 * 1024;
type SubmitState = "idle" | "loading" | "success" | "error";
type FieldErrors = Partial<Record<"vehicle" | "year" | "part" | "photo" | "contact", string>>;
type FunnelEvent = "landing_view" | "request_start" | "request_submit" | "request_error";
function attribution(){const p=new URLSearchParams(window.location.search);let r="";try{r=document.referrer?new URL(document.referrer).hostname:""}catch{}return{source:p.get("utm_source")||undefined,medium:p.get("utm_medium")||undefined,campaign:p.get("utm_campaign")||undefined,referrerHost:r||undefined}}
export default function Home(){
 const[state,setState]=useState<SubmitState>("idle"),[message,setMessage]=useState(""),[fieldErrors,setFieldErrors]=useState<FieldErrors>({}),[requestNumber,setRequestNumber]=useState<number|null>(null);const sessionId=useRef(""),started=useRef(false);
 function track(eventName:FunnelEvent){if(!sessionId.current)return;void fetch(ANALYTICS_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},keepalive:true,body:JSON.stringify({eventName,sessionId:sessionId.current,...attribution()})}).catch(()=>undefined)}
 useEffect(()=>{sessionId.current=crypto.randomUUID();track("landing_view")},[]);
 function markRequestStart(){if(started.current)return;started.current=true;track("request_start")}
 function focusField(form:HTMLFormElement,name:string){const f=form.elements.namedItem(name);if(f instanceof HTMLElement){f.focus();f.scrollIntoView({behavior:"smooth",block:"center"})}}
 function failField(form:HTMLFormElement,errors:FieldErrors,name:string){setFieldErrors(errors);setState("error");setMessage("");requestAnimationFrame(()=>focusField(form,name))}
 async function submitRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();if(state==="loading")return;const form=event.currentTarget,v=new FormData(form),text=(n:string)=>String(v.get(n)??"").trim(),contact=text("contact"),vin=text("vin"),carMake=text("carMake"),carModel=text("carModel"),carYear=text("carYear"),partName=text("partName"),partNumber=text("partNumber"),description=text("description"),photo=v.get("photo"),hasPhoto=photo instanceof File&&photo.size>0;setFieldErrors({});setMessage("");
 if(!vin&&!(carMake&&carModel&&carYear)){failField(form,{vehicle:"Укажите VIN или марку, модель и год автомобиля."},"vin");return}if(carYear){const y=Number(carYear);if(!Number.isInteger(y)||y<1950||y>2100){failField(form,{year:"Проверьте год автомобиля."},"carYear");return}}if(!partName&&!partNumber&&!description&&!hasPhoto){failField(form,{part:"Добавьте название, OEM/Part Number, описание или фото детали."},"partName");return}if(hasPhoto&&photo instanceof File){if(!photo.type.startsWith("image/")){failField(form,{photo:"Можно загружать только изображения."},"photo");return}if(photo.size>MAX_PHOTO_BYTES){failField(form,{photo:"Фотография слишком большая. Максимум 8 МБ."},"photo");return}}if(!contact){failField(form,{contact:"Укажите телефон, WhatsApp или Telegram."},"contact");return}
 const photoKeys=hasPhoto?["part-0-photo-0"]:[],body=new FormData();for(const key of["contact","clientName","vin","carMake","carModel","carYear","website"]){const value=v.get(key);if(typeof value==="string")body.set(key,value)}body.set("analyticsSession",sessionId.current);body.set("parts",JSON.stringify([{partName,partNumber,description,photoKeys}]));if(photoKeys.length&&photo instanceof File)body.set(photoKeys[0],photo);setState("loading");track("request_submit");try{const response=await fetch(ENDPOINT,{method:"POST",body}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Не удалось отправить заявку");setRequestNumber(data.requestNumber??null);setState("success");form.reset()}catch(error){track("request_error");setMessage(error instanceof Error?error.message:"Не удалось отправить заявку");setState("error")}}
 return <main><header className="topbar"><a className="brand" href="#top" aria-label="Spline"><img src="/spline-wordmark.svg" width="103" height="24" alt="Spline" /></a><a className="topCta" href="#request">Найти деталь</a></header>
 <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">Parts sourcing · UAE</p><h1>Нужна запчасть? Покажите машину и деталь.</h1><p className="lead">Отправьте VIN, данные автомобиля, фото или OEM‑номер. Менеджер получит всё в одной заявке и продолжит подбор.</p><div className="heroActions"><a className="primary" href="#request">Запросить запчасть</a><span className="micro">Без каталога и долгого поиска по сайту.</span></div></div><aside className="sourcingTicket" aria-label="Что можно отправить для поиска детали"><div className="ticketHead"><span>PART REQUEST</span><span>UAE / SPLINE</span></div><div className="ticketRow"><span className="ticketCode">VEHICLE ID</span><strong>VIN</strong><small>или марка · модель · год</small></div><div className="ticketRow"><span className="ticketCode">PART ID</span><strong>Фото / OEM / название</strong><small>достаточно любого понятного признака</small></div><div className="ticketRow ticketRowLast"><span className="ticketCode">CONTACT</span><strong>Телефон / WhatsApp / Telegram</strong><small>для ответа менеджера</small></div></aside></section>
 <section className="process"><div className="sectionHead"><p className="eyebrow">Как это работает</p><h2>Одна заявка. Три понятных блока.</h2></div><div className="processRail"><article><span>01 / VEHICLE</span><h3>Покажите автомобиль</h3><p>VIN либо марка, модель и год.</p></article><article><span>02 / PART</span><h3>Покажите деталь</h3><p>Фото, название, OEM‑номер или короткое описание.</p></article><article><span>03 / CONTACT</span><h3>Оставьте контакт</h3><p>Заявка отправится в рабочий процесс Spline.</p></article></div></section>
 <section className="requestSection" id="request"><div className="requestIntro"><p className="eyebrow">Request a part</p><h2>Что нужно найти?</h2><p>Не обязательно заполнять всё. Для автомобиля достаточно VIN либо марки, модели и года. Для детали — любого понятного признака.</p><div className="requestLegend" aria-label="Что можно использовать в заявке"><span>VIN</span><span>OEM</span><span>PHOTO</span><span>VEHICLE</span></div></div>{state==="success"?<div className="success" role="status"><span>REQUEST RECEIVED</span><h2>{requestNumber?`Заявка №${requestNumber}`:"Заявка принята"}</h2><p>Она уже находится в рабочей системе Spline.</p><button className="secondary" onClick={()=>{started.current=false;setState("idle")}}>Отправить ещё одну</button></div>:<form onSubmit={submitRequest} onFocusCapture={markRequestStart} onChange={markRequestStart} className="requestForm" noValidate><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" />
 <fieldset aria-describedby={fieldErrors.vehicle?"vehicle-error":undefined}><legend><span>01</span> Автомобиль</legend><p className="fieldNote">VIN — самый короткий путь. Если его нет под рукой, укажите данные автомобиля.</p><label>VIN<input name="vin" placeholder="Например: JT..." autoCapitalize="characters" aria-invalid={fieldErrors.vehicle?"true":undefined}/></label>{fieldErrors.vehicle&&<p className="fieldError" id="vehicle-error" role="alert">{fieldErrors.vehicle}</p>}<div className="or"><span>или</span></div><div className="grid3"><label>Марка<input name="carMake" placeholder="Toyota"/></label><label>Модель<input name="carModel" placeholder="Camry"/></label><label>Год<input name="carYear" inputMode="numeric" placeholder="2022" aria-invalid={fieldErrors.year?"true":undefined} aria-describedby={fieldErrors.year?"year-error":undefined}/></label></div>{fieldErrors.year&&<p className="fieldError" id="year-error" role="alert">{fieldErrors.year}</p>}</fieldset>
 <fieldset aria-describedby={fieldErrors.part?"part-error":undefined}><legend><span>02</span> Деталь</legend><p className="fieldNote">Можно отправить название, номер или фотографию — необязательно знать всё сразу.</p><label>Название детали<input name="partName" placeholder="Например: передняя фара" aria-invalid={fieldErrors.part?"true":undefined}/></label>{fieldErrors.part&&<p className="fieldError" id="part-error" role="alert">{fieldErrors.part}</p>}<label>OEM / Part Number<input name="partNumber" placeholder="Если известен"/></label><label className="fileLabel">Фото детали<input name="photo" type="file" accept="image/*" aria-invalid={fieldErrors.photo?"true":undefined} aria-describedby={fieldErrors.photo?"photo-error":undefined}/></label>{fieldErrors.photo&&<p className="fieldError" id="photo-error" role="alert">{fieldErrors.photo}</p>}<label>Комментарий<textarea name="description" rows={3} placeholder="Сторона, повреждение или любая полезная деталь"/></label></fieldset>
 <fieldset aria-describedby={fieldErrors.contact?"contact-error":undefined}><legend><span>03</span> Контакт</legend><p className="fieldNote">Укажите удобный контакт, чтобы менеджер мог продолжить подбор.</p><label>Телефон / WhatsApp / Telegram<input name="contact" placeholder="Как с вами связаться" aria-invalid={fieldErrors.contact?"true":undefined} aria-describedby={fieldErrors.contact?"contact-error":undefined}/></label>{fieldErrors.contact&&<p className="fieldError" id="contact-error" role="alert">{fieldErrors.contact}</p>}<label>Имя <span>(необязательно)</span><input name="clientName" placeholder="Ваше имя"/></label></fieldset>{state==="error"&&message&&<p className="error" role="alert">{message}</p>}<button className="primary submit" disabled={state==="loading"} type="submit">{state==="loading"?"Отправляем…":"Отправить заявку"}</button></form>}</section></main>}
